parameters:
    nelmio_security.clickjacking_listener.class: Nelmio\SecurityBundle\EventListener\ClickjackingListener

services:
    nelmio_security.clickjacking_listener:
        scope: request
        class: %nelmio_security.clickjacking_listener.class%
        arguments:
            - %nelmio_security.clickjacking.paths%
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
