parameters:
    nelmio_security.content_type_listener.class: Nelmio\SecurityBundle\EventListener\ContentTypeListener

services:
    nelmio_security.content_type_listener:
        scope: request
        class: %nelmio_security.content_type_listener.class%
        arguments:
            - %nelmio_security.content_type.nosniff%

        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
