parameters:
    nelmio_security.external_redirects.whitelist: ~
    nelmio_security.external_redirect_listener.class: Nelmio\SecurityBundle\EventListener\ExternalRedirectListener

services:
    nelmio_security.external_redirect_listener:
        scope: request
        class: %nelmio_security.external_redirect_listener.class%
        arguments:
            - %nelmio_security.external_redirects.abort%
            - %nelmio_security.external_redirects.override%
            - %nelmio_security.external_redirects.forward_as%
            - %nelmio_security.external_redirects.whitelist%
            - @?logger
            - @?router
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
            - { name: monolog.logger, channel: security }
